/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  // static const String passwordless = "assets/images/passwordless.png";
  static const String shoppingAppLogo = "assets/images/123.png";
}
